// src/app/detail/detail.component.ts
import { ChangeDetectionStrategy, Component, computed, Signal } from '@angular/core'
import { MatIconButton } from '@angular/material/button'
import { MatIcon } from '@angular/material/icon'
import { Store } from '@ngrx/store'
import { RootState } from 'src/store/app.store'
import { TransitLinesActions } from 'src/store/transit-lines/transit-lines.actions'
import { fromTransitLines } from 'src/store/transit-lines/transit-lines.selectors'

@Component({
  selector: 'app-detail',
  templateUrl: './detail.component.html',
  styleUrls: ['./detail.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [MatIconButton, MatIcon],
})
export class DetailComponent {
  readonly stopName: Signal<string>

  constructor(private store: Store<RootState>) {
    const selectedStop = this.store.selectSignal(fromTransitLines.selectedStop)
    this.stopName = computed(() => selectedStop()?.name || 'No selection')
  }

  clearSelection(): void {
    this.store.dispatch(TransitLinesActions.SelectStop({ selectedStopId: null }))
  }
}

<div class="detail-header">
  <h1 class="title">{{ stopName() }}</h1>
  <button mat-icon-button (click)="clearSelection()">
    <mat-icon>clear</mat-icon>
  </button>
</div>

<span>Its very empty here (ಠ_ಠ)</span>

<!-- TODO add more info about the stop -->

// src/App/Detail/Detail.tsx
import React from 'react'
import './Detail.scss'

import { IconButton } from '@mui/material'
import { Clear } from '@mui/icons-material'
import { useDispatch, useSelector } from 'react-redux'

import { fromTransitLines } from 'store/transit-lines/transit-lines.selectors'
import { TransitLineActions } from 'store/transit-lines/transit-lines.actions'

function Detail() {
  const dispatch = useDispatch()
  const selectedStop = useSelector(fromTransitLines.selectedStop)

  const clearSelection = (): void => {
    dispatch(TransitLineActions.SelectStop(null))
  }

  return (
    <div className="detail">
      <div className="detail-header">
        <h1 className="title">{selectedStop?.name || 'No selection'}</h1>
        <IconButton className="button" onClick={clearSelection}>
          <Clear className="icon" />
        </IconButton>
      </div>

      <span>Its very empty here (ಠ_ಠ)</span>

      {/*TODO add more info about the stop*/}
    </div>
  )
}

export default Detail
