// src/app/home/home.component.ts
import { Component } from '@angular/core'
import { select, Store } from '@ngrx/store'
import { Observable } from 'rxjs'
import { RootState } from 'src/store/app.store'
import { TransitLinesActions } from 'src/store/transit-lines/transit-lines.actions'
import { fromTransitLines } from 'src/store/transit-lines/transit-lines.selectors'
import { TransitStop } from 'src/types/stop'

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss'],
})
export class HomeComponent {
  lines$: Observable<{ lineId: string; numberOfStops: number; stops: TransitStop[] }[]>

  constructor(private store: Store<RootState>) {
    this.lines$ = store.pipe(select(fromTransitLines.linesList))
  }

  selectStop(selectedStopId: string): void {
    this.store.dispatch(TransitLinesActions.SelectStop({ selectedStopId }))
  }
}

<h1 class="title">All Lines</h1>

<div class="lines-list">
  <div class="line-item" *ngFor="let line of lines$ | async">
    <div class="line-header">
      <mat-icon>directions_transit</mat-icon>
      <h2 class="subtitle">{{line.lineId}}</h2>
      <span class="stops-count">{{line.numberOfStops}} Stops</span>
    </div>
    <div class="stops-list">
      <div (click)="selectStop(stop.stopId)" class="stop-item" *ngFor="let stop of line.stops">
        <mat-icon>stop_circle</mat-icon>
        <span>{{stop.name}}</span>
      </div>
    </div>
  </div>
</div>

<!-- TODO add the possibility to collapese/expand the list of stops -->

<!-- TODO add ad visulaization of the stops properties -->

// src/App/Home/Home.tsx
import React from 'react'
import './Home.scss'

import { useDispatch, useSelector } from 'react-redux'
import { DirectionsTransit, StopCircle } from '@mui/icons-material'

import { fromTransitLines } from 'store/transit-lines/transit-lines.selectors'
import { TransitLineActions } from 'store/transit-lines/transit-lines.actions'

function Home() {
  const dispatch = useDispatch()
  const lines = useSelector(fromTransitLines.linesList)

  const selectStop = (selectedStopId: string): void => {
    dispatch(TransitLineActions.SelectStop(selectedStopId))
  }

  return (
    <div className="home">
      <h1 className="title">All Lines</h1>

      <div className="lines-list">
        {lines.map((line) => (
          <div className="line-item" key={line.lineId}>
            <div className="line-header">
              <DirectionsTransit className="icon" />
              <h2 className="subtitle">{line.lineId}</h2>
              <span className="stops-count">{line.numberOfStops} Stops</span>
            </div>

            <div className="stops-list">
              {line.stops.map((stop) => (
                <div onClick={() => selectStop(stop.stopId)} className="stop-item" key={stop.stopId}>
                  <StopCircle className="icon" />
                  <span>{stop.name}</span>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

export default Home
